steps:
# step 0 store build info
- id: "Store Values"
  name: ubuntu
  entrypoint: bash
  args:
    - -c
    - |
      # save the commit sha & build date
      NOW=$(date +"%Y-%m-%d %T")
      echo $BRANCH_NAME $SHORT_SHA $$NOW > BUILDINFO
      # update version
      # cat VERSION | awk -F. '/[0-9]+\./{$$NF++;print}' OFS=. | tee VERSION
      echo $(perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' < VERSION) > VERSION
      VERSION=$(cat VERSION)
      # Replace version in k8s/kustomization.yaml
      sed -i "s#VERSION#$(cat VERSION)#g" k8s/kustomization.yaml
      # Replace image in k8s/kustomization.yaml
      sed -i "s#IMAGE_NAME#gcr.io/$PROJECT_ID/psilogin#g" k8s/kustomization.yaml
      # Replace image tag in k8s/kustomization.yaml
      sed -i "s#IMAGE_TAG#$SHORT_SHA#g" k8s/kustomization.yaml
      # Replace overlay in k8s/kustomization.yaml
      sed -i "s#BRANCH#$BRANCH_NAME#g" k8s/kustomization.yaml
      cat k8s/kustomization.yaml
- id: "Build Container Image"
  name: 'gcr.io/kaniko-project/executor:latest'
  args: [
    '--destination=gcr.io/$PROJECT_ID/psilogin:$SHORT_SHA',
    '--destination=gcr.io/$PROJECT_ID/psilogin:latest',
    '--build-arg', 'COMMITSHA=$COMMIT_SHA',
    '--build-arg', 'SHORTSHA=$SHORT_SHA',
    '--cache=true',
    '--cache-ttl=336h'
  ]
- id: deploy
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-k', './k8s']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
substitutions:
  _APP_NAME: 'psilogin'